part of 'downloads_bloc.dart';

const test = [
  {
    "backdrop_path": "/wIZ6cPH9lGC03gM0U6Es05afcSZ.jpg",
    "id": 1233413,
    "title": "Sinners",
    "original_title": "Sinners",
    "overview":
        "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
    "poster_path": "/jYfMTSiFFK7ffbY2lay4zyvTkEk.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [27, 53],
    "popularity": 238.7202,
    "release_date": "2025-04-16",
    "video": false,
    "vote_average": 7.51,
    "vote_count": 962,
  },
  {
    "backdrop_path": "/8GZQMdep33NMdeIyV0ur0JMXZIO.jpg",
    "id": 1417059,
    "title": "Mountainhead",
    "original_title": "Mountainhead",
    "overview":
        "A group of billionaire friends get together against the backdrop of a rolling international crisis.",
    "poster_path": "/jZKK5mFKWbquxhAGMkRJtNYwk0I.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [18, 35],
    "popularity": 130.6186,
    "release_date": "2025-05-22",
    "video": false,
    "vote_average": 5.977,
    "vote_count": 22,
  },
  {
    "backdrop_path": "/3VkPqpjKikQg2M2n6xgTfR9xr7E.jpg",
    "id": 575265,
    "title": "Mission: Impossible - The Final Reckoning",
    "original_title": "Mission: Impossible - The Final Reckoning",
    "overview":
        "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
    "poster_path": "/iKPsC9EFUafRP9SrUznI61getVP.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 12, 53],
    "popularity": 278.0627,
    "release_date": "2025-05-17",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 535,
  },
  {
    "backdrop_path": "/pOR4Aye28KLZ5Jogu8zc3yiqBpT.jpg",
    "id": 1397832,
    "title": "A Widow's Game",
    "original_title": "La viuda negra",
    "overview":
        "When a man is found dead, the investigation shatters his widow's perfect facade and exposes a hidden double life in this thriller based on real events.",
    "poster_path": "/yZOdrJDl2GwREoigC0y40kMosxj.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "es",
    "genre_ids": [53, 9648],
    "popularity": 112.0693,
    "release_date": "2025-05-29",
    "video": false,
    "vote_average": 6.2,
    "vote_count": 48,
  },
  {
    "backdrop_path": "/v67tbCB03CMcJRWit8CS7JdJp6.jpg",
    "id": 757725,
    "title": "Shadow Force",
    "original_title": "Shadow Force",
    "overview":
        "Kyrah and Isaac were once the leaders of a multinational special forces group called Shadow Force. They broke the rules by falling in love, and in order to protect their son, they go underground. With a large bounty on their heads, and the vengeful Shadow Force hot on their trail, one family's fight becomes all-out war.",
    "poster_path": "/uX6FaNE86a4Xnf1mFFEryvjqB1D.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 53, 18],
    "popularity": 34.949,
    "release_date": "2025-05-01",
    "video": false,
    "vote_average": 6.115,
    "vote_count": 26,
  },
  {
    "backdrop_path": "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
    "id": 552524,
    "title": "Lilo & Stitch",
    "original_title": "Lilo & Stitch",
    "overview":
        "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
    "poster_path": "/tUae3mefrDVTgm5mRzqWnZK6fOP.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [10751, 35, 878],
    "popularity": 736.864,
    "release_date": "2025-05-17",
    "video": false,
    "vote_average": 7.103,
    "vote_count": 389,
  },
  {
    "backdrop_path": "/jfnFHHZSIPkHfKGjlWnWck2o5ou.jpg",
    "id": 1165642,
    "title": "Lost in Starlight",
    "original_title": "이 별에 필요한",
    "overview":
        "When an astronaut leaves Earth for Mars, the vast infinite space divides star-crossed lovers in this animated romance that crosses the cosmos.",
    "poster_path": "/dXlUIfwejWa9YvugU9V773dUASY.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "ko",
    "genre_ids": [16, 10749, 878],
    "popularity": 87.1996,
    "release_date": "2025-05-30",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 18,
  },
  {
    "backdrop_path": "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
    "id": 574475,
    "title": "Final Destination Bloodlines",
    "original_title": "Final Destination Bloodlines",
    "overview":
        "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
    "poster_path": "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [27, 9648],
    "popularity": 372.564,
    "release_date": "2025-05-14",
    "video": false,
    "vote_average": 6.97,
    "vote_count": 541,
  },
  {
    "backdrop_path": "/8eifdha9GQeZAkexgtD45546XKx.jpg",
    "id": 822119,
    "title": "Captain America: Brave New World",
    "original_title": "Captain America: Brave New World",
    "overview":
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
    "poster_path": "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 53, 878],
    "popularity": 170.2844,
    "release_date": "2025-02-12",
    "video": false,
    "vote_average": 6.073,
    "vote_count": 2037,
  },
  {
    "backdrop_path": "/kEYWal656zP5Q2Tohm91aw6orlT.jpg",
    "id": 1064213,
    "title": "Anora",
    "original_title": "Anora",
    "overview":
        "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
    "poster_path": "/7MrgIUeq0DD2iF7GR6wqJfYZNeC.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [18, 35, 10749],
    "popularity": 84.0977,
    "release_date": "2024-10-14",
    "video": false,
    "vote_average": 7.054,
    "vote_count": 2229,
  },
  {
    "backdrop_path": "/5IbxcBXZ5EhVAttfNDMPncikudr.jpg",
    "id": 541671,
    "title": "From the World of John Wick: Ballerina",
    "original_title": "From the World of John Wick: Ballerina",
    "overview":
        "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    "poster_path": "/mKp4euM5Cv3m2U1Vmby3OGwcD5y.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 53, 80],
    "popularity": 45.847,
    "release_date": "2025-06-06",
    "video": false,
    "vote_average": 7.5,
    "vote_count": 2,
  },
  {
    "backdrop_path": "/lAnkMSDISzMYLWICS7m16rSTUHD.jpg",
    "id": 1011477,
    "title": "Karate Kid: Legends",
    "original_title": "Karate Kid: Legends",
    "overview":
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
    "poster_path": "/AEgggzRr1vZCLY86MAp93li43z.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 12, 18],
    "popularity": 102.2284,
    "release_date": "2025-05-08",
    "video": false,
    "vote_average": 7.228,
    "vote_count": 68,
  },
  {
    "backdrop_path": "/aESb695wTIF0tB7RTGRebnYrjFK.jpg",
    "id": 1098006,
    "title": "Fountain of Youth",
    "original_title": "Fountain of Youth",
    "overview":
        "A treasure-hunting mastermind assembles a team for a life-changing adventure. But to outwit and outrun threats at every turn, he'll need someone even smarter than he is: his estranged sister.",
    "poster_path": "/4iWjGghUj2uyHo2Hyw8NFBvsNGm.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [12, 14, 9648],
    "popularity": 158.2408,
    "release_date": "2025-05-19",
    "video": false,
    "vote_average": 6.5,
    "vote_count": 364,
  },
  {
    "backdrop_path": "/hQ3naChF8XajGCRcvOX5TLVSqQd.jpg",
    "id": 1197137,
    "title": "Black Phone 2",
    "original_title": "Black Phone 2",
    "overview":
        "Set several years after the events of the first film, The Black Phone 2 reunites us with survivors Finney and Gwen as they attempt to move forward. But the past refuses to stay buried. When a new string of disappearances strikes the area, it becomes clear that something—or someone—has returned. And the black phone? It’s ringing again.",
    "poster_path": "/tx6qaUR8r2qglIKpZOsfshjJrS8.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [27, 53],
    "popularity": 2.9267,
    "release_date": "2024-10-16",
    "video": false,
    "vote_average": 0,
    "vote_count": 0,
  },
  {
    "backdrop_path": "/icFWIk1KfkWLZnugZAJEDauNZ94.jpg",
    "id": 1232546,
    "title": "Until Dawn",
    "original_title": "Until Dawn",
    "overview":
        "One year after her sister Melanie mysteriously disappeared, Clover and her friends head into the remote valley where she vanished in search of answers. Exploring an abandoned visitor center, they find themselves stalked by a masked killer and horrifically murdered one by one...only to wake up and find themselves back at the beginning of the same evening.",
    "poster_path": "/juA4IWO52Fecx8lhAsxmDgy3M3.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [27, 9648],
    "popularity": 246.5215,
    "release_date": "2025-04-23",
    "video": false,
    "vote_average": 6.476,
    "vote_count": 537,
  },
  {
    "backdrop_path": "/2Nti3gYAX513wvhp8IiLL6ZDyOm.jpg",
    "id": 950387,
    "title": "A Minecraft Movie",
    "original_title": "A Minecraft Movie",
    "overview":
        "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
    "poster_path": "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [10751, 35, 12, 14],
    "popularity": 457.1268,
    "release_date": "2025-03-31",
    "video": false,
    "vote_average": 6.494,
    "vote_count": 1603,
  },
  {
    "backdrop_path": "/2aBRKrISNFi1fAfDNexh4zsnUG4.jpg",
    "id": 1154478,
    "title": "I Am What I Am 2",
    "original_title": "雄狮少年2",
    "overview":
        "Ah juan, an unknown person who came to Shanghai to work, agreed to represent the declining Chuanwu Boxing Gym to participate in the \"Shanghai Fight Night\" martial arts competition in order to earn money to treat his father's illness. To do so, he must overcome all the experts, prejudices, and himself.",
    "poster_path": "/vuAs1O1AdBhcr3l1hWeiv260J4O.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "zh",
    "genre_ids": [16, 28, 35],
    "popularity": 3.9215,
    "release_date": "2024-12-07",
    "video": false,
    "vote_average": 8.167,
    "vote_count": 6,
  },
  {
    "backdrop_path": "/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg",
    "id": 1087192,
    "title": "How to Train Your Dragon",
    "original_title": "How to Train Your Dragon",
    "overview":
        "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    "poster_path": "/47HoQdGvW4Jy4ntUbsQ3bEnJHDh.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 10751, 14],
    "popularity": 48.2865,
    "release_date": "2025-06-06",
    "video": false,
    "vote_average": 0,
    "vote_count": 0,
  },
  {
    "backdrop_path": "/z5caDtY3tn6rwbzB8iIA8PFCqYN.jpg",
    "id": 1245165,
    "title": "Graduation Trip: Mallorca",
    "original_title": "Viaje de fin de curso: Mallorca",
    "overview":
        "2021. After spending a year in confinement, a group of high school students and their two teachers begin an end-of-year trip to Mallorca. This great plan is the last opportunity they have to all be together, make up for lost time, be able to have fun like they have never had before and say goodbye to this crazy stage of their lives. However, a new coronavirus outbreak disrupts all their plans and forces them to stay locked in their hotel rooms. More than 50 students, 2 teachers, a hotel and many, many minibars... What could go wrong?",
    "poster_path": "/ejYX4ygRoupGRjFgmmtnK0sMxhN.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "es",
    "genre_ids": [35],
    "popularity": 114.6037,
    "release_date": "2025-05-30",
    "video": false,
    "vote_average": 5.6,
    "vote_count": 15,
  },
  {
    "backdrop_path": "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
    "id": 986056,
    "title": "Thunderbolts*",
    "original_title": "Thunderbolts*",
    "overview":
        "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
    "poster_path": "/m9EtP1Yrzv6v7dMaC9mRaGhd1um.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 878, 12],
    "popularity": 133.0243,
    "release_date": "2025-04-30",
    "video": false,
    "vote_average": 7.413,
    "vote_count": 1060,
  },
];

final List<Downloads> testDownloads = test
    .map((movieMap) => Downloads.fromJson(movieMap))
    .toList();

@freezed
abstract class DownloadsState with _$DownloadsState {
  const factory DownloadsState({
    required bool isLoading,
    required List<Downloads>? downloads,
    required Option<Either<MainFailure, List<Downloads>>>
    downloadsFailureOrSuccessOption,
  }) = _DownloadState;

  factory DownloadsState.initial() {
    return DownloadsState(
      isLoading: false,
      downloadsFailureOrSuccessOption: None(),
      downloads: testDownloads,
    );
  }
}
