part of 'search_bloc.dart';

const topIdle = [
  {
    "adult": false,
    "backdrop_path": "/2PDTWfuBWQKVC7aPAqJK5UCpz08.jpg",
    "genre_ids": [28, 878],
    "id": 557,
    "original_language": "en",
    "original_title": "Spider-Man",
    "overview":
        "After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.",
    "popularity": 27.6468,
    "poster_path": "/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg",
    "release_date": "2002-05-01",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 7.311,
    "vote_count": 19625,
  },
  {
    "adult": false,
    "backdrop_path": "/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 569094,
    "original_language": "en",
    "original_title": "Spider-Man: Across the Spider-Verse",
    "overview":
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    "popularity": 32.8095,
    "poster_path": "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "release_date": "2023-05-31",
    "title": "Spider-Man: Across the Spider-Verse",
    "video": false,
    "vote_average": 8.345,
    "vote_count": 7602,
  },

  {
    "backdrop_path": "/8GZQMdep33NMdeIyV0ur0JMXZIO.jpg",
    "id": 1417059,
    "title": "Mountainhead",
    "original_title": "Mountainhead",
    "overview":
        "A group of billionaire friends get together against the backdrop of a rolling international crisis.",
    "poster_path": "/jZKK5mFKWbquxhAGMkRJtNYwk0I.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [18, 35],
    "popularity": 130.6186,
    "release_date": "2025-05-22",
    "video": false,
    "vote_average": 5.977,
    "vote_count": 22,
  },
  {
    "backdrop_path": "/3VkPqpjKikQg2M2n6xgTfR9xr7E.jpg",
    "id": 575265,
    "title": "Mission: Impossible - The Final Reckoning",
    "original_title": "Mission: Impossible - The Final Reckoning",
    "overview":
        "Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world's governments and a mysterious ghost from Hunt's past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.",
    "poster_path": "/iKPsC9EFUafRP9SrUznI61getVP.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 12, 53],
    "popularity": 278.0627,
    "release_date": "2025-05-17",
    "video": false,
    "vote_average": 7.1,
    "vote_count": 535,
  },
  {
    "backdrop_path": "/pOR4Aye28KLZ5Jogu8zc3yiqBpT.jpg",
    "id": 1397832,
    "title": "A Widow's Game",
    "original_title": "La viuda negra",
    "overview":
        "When a man is found dead, the investigation shatters his widow's perfect facade and exposes a hidden double life in this thriller based on real events.",
    "poster_path": "/yZOdrJDl2GwREoigC0y40kMosxj.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "es",
    "genre_ids": [53, 9648],
    "popularity": 112.0693,
    "release_date": "2025-05-29",
    "video": false,
    "vote_average": 6.2,
    "vote_count": 48,
  },
  {
    "backdrop_path": "/v67tbCB03CMcJRWit8CS7JdJp6.jpg",
    "id": 757725,
    "title": "Shadow Force",
    "original_title": "Shadow Force",
    "overview":
        "Kyrah and Isaac were once the leaders of a multinational special forces group called Shadow Force. They broke the rules by falling in love, and in order to protect their son, they go underground. With a large bounty on their heads, and the vengeful Shadow Force hot on their trail, one family's fight becomes all-out war.",
    "poster_path": "/uX6FaNE86a4Xnf1mFFEryvjqB1D.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [28, 53, 18],
    "popularity": 34.949,
    "release_date": "2025-05-01",
    "video": false,
    "vote_average": 6.115,
    "vote_count": 26,
  },
  {
    "backdrop_path": "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
    "id": 552524,
    "title": "Lilo & Stitch",
    "original_title": "Lilo & Stitch",
    "overview":
        "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
    "poster_path": "/tUae3mefrDVTgm5mRzqWnZK6fOP.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [10751, 35, 878],
    "popularity": 736.864,
    "release_date": "2025-05-17",
    "video": false,
    "vote_average": 7.103,
    "vote_count": 389,
  },
  {
    "backdrop_path": "/jfnFHHZSIPkHfKGjlWnWck2o5ou.jpg",
    "id": 1165642,
    "title": "Lost in Starlight",
    "original_title": "이 별에 필요한",
    "overview":
        "When an astronaut leaves Earth for Mars, the vast infinite space divides star-crossed lovers in this animated romance that crosses the cosmos.",
    "poster_path": "/dXlUIfwejWa9YvugU9V773dUASY.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "ko",
    "genre_ids": [16, 10749, 878],
    "popularity": 87.1996,
    "release_date": "2025-05-30",
    "video": false,
    "vote_average": 7.3,
    "vote_count": 18,
  },
  {
    "backdrop_path": "/uIpJPDNFoeX0TVml9smPrs9KUVx.jpg",
    "id": 574475,
    "title": "Final Destination Bloodlines",
    "original_title": "Final Destination Bloodlines",
    "overview":
        "Plagued by a violent recurring nightmare, college student Stefanie heads home to track down the one person who might be able to break the cycle and save her family from the grisly demise that inevitably awaits them all.",
    "poster_path": "/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg",
    "media_type": "movie",
    "adult": false,
    "original_language": "en",
    "genre_ids": [27, 9648],
    "popularity": 372.564,
    "release_date": "2025-05-14",
    "video": false,
    "vote_average": 6.97,
    "vote_count": 541,
  },
  {
    "adult": false,
    "backdrop_path": "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 324857,
    "original_language": "en",
    "original_title": "Spider-Man: Into the Spider-Verse",
    "overview":
        "Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson \"Kingpin\" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.",
    "popularity": 15.1054,
    "poster_path": "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    "release_date": "2018-12-06",
    "title": "Spider-Man: Into the Spider-Verse",
    "video": false,
    "vote_average": 8.398,
    "vote_count": 16166,
  },
  {
    "adult": false,
    "backdrop_path": "/zD5v1E4joAzFvmAEytt7fM3ivyT.jpg",
    "genre_ids": [28, 12, 878],
    "id": 634649,
    "original_language": "en",
    "original_title": "Spider-Man: No Way Home",
    "overview":
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    "popularity": 33.9416,
    "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "release_date": "2021-12-15",
    "title": "Spider-Man: No Way Home",
    "video": false,
    "vote_average": 7.945,
    "vote_count": 20796,
  },

  {
    "adult": false,
    "backdrop_path": "/63JYqhefGrbVg0YqZ3xWqn0pwT2.jpg",
    "genre_ids": [878, 28, 12],
    "id": 969681,
    "original_language": "en",
    "original_title": "Spider-Man: Brand New Day",
    "overview":
        "The fourth installment in the MCU Spider-Man franchise. Plot TBA.",
    "popularity": 5.7388,
    "poster_path": "/9JCQtDCSpPR2ld55yNlEg1VwcQo.jpg",
    "release_date": "2026-07-30",
    "title": "Spider-Man: Brand New Day",
    "video": false,
    "vote_average": 0,
    "vote_count": 0,
  },
  {
    "adult": false,
    "backdrop_path": "/gC4srY5pUJ2zpo6lxWiedCUKzDc.jpg",
    "genre_ids": [],
    "id": 68658,
    "original_language": "en",
    "original_title": "Spiderman",
    "overview":
        "One minute he's Peter Parker the college student, and the next he's Spiderman!",
    "popularity": 0.0338,
    "poster_path": "/3HakxkortobYPDd7tRqKWM9PyxQ.jpg",
    "release_date": "1990-01-01",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 8,
    "vote_count": 31,
  },
];

const searches = [
  {
    "adult": false,
    "backdrop_path": "/2PDTWfuBWQKVC7aPAqJK5UCpz08.jpg",
    "genre_ids": [28, 878],
    "id": 557,
    "original_language": "en",
    "original_title": "Spider-Man",
    "overview":
        "After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.",
    "popularity": 22.9677,
    "poster_path": "/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg",
    "release_date": "2002-05-01",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 7.311,
    "vote_count": 19626,
  },
  {
    "adult": false,
    "backdrop_path": "/kVd3a9YeLGkoeR50jGEXM6EqseS.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 569094,
    "original_language": "en",
    "original_title": "Spider-Man: Across the Spider-Verse",
    "overview":
        "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.",
    "popularity": 29.0628,
    "poster_path": "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    "release_date": "2023-05-31",
    "title": "Spider-Man: Across the Spider-Verse",
    "video": false,
    "vote_average": 8.343,
    "vote_count": 7605,
  },
  {
    "adult": false,
    "backdrop_path": "/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 324857,
    "original_language": "en",
    "original_title": "Spider-Man: Into the Spider-Verse",
    "overview":
        "Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson \"Kingpin\" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.",
    "popularity": 14.3969,
    "poster_path": "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    "release_date": "2018-12-06",
    "title": "Spider-Man: Into the Spider-Verse",
    "video": false,
    "vote_average": 8.398,
    "vote_count": 16168,
  },
  {
    "adult": false,
    "backdrop_path": "/zD5v1E4joAzFvmAEytt7fM3ivyT.jpg",
    "genre_ids": [28, 12, 878],
    "id": 634649,
    "original_language": "en",
    "original_title": "Spider-Man: No Way Home",
    "overview":
        "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    "popularity": 29.6721,
    "poster_path": "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "release_date": "2021-12-15",
    "title": "Spider-Man: No Way Home",
    "video": false,
    "vote_average": 7.945,
    "vote_count": 20798,
  },
  {
    "adult": false,
    "backdrop_path": "/tPpYGm2mVecue7Bk3gNVoSPA5qn.jpg",
    "genre_ids": [28, 12, 878, 18],
    "id": 315635,
    "original_language": "en",
    "original_title": "Spider-Man: Homecoming",
    "overview":
        "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
    "popularity": 139.5865,
    "poster_path": "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    "release_date": "2017-07-05",
    "title": "Spider-Man: Homecoming",
    "video": false,
    "vote_average": 7.331,
    "vote_count": 22232,
  },
  {
    "adult": false,
    "backdrop_path": null,
    "genre_ids": [28, 878],
    "id": 445033,
    "original_language": "en",
    "original_title": "Spider-Man",
    "overview":
        "Spider-man must rescue the beautiful daughter of the evil Dr. Lightning.",
    "popularity": 0.8603,
    "poster_path": "/xfmZECbfYx672XIshP6dPt5K5jI.jpg",
    "release_date": "1969-01-01",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 7.7,
    "vote_count": 49,
  },
  {
    "adult": false,
    "backdrop_path": "/w1oD1MzHjnBJc5snKupIQaSBLIh.jpg",
    "genre_ids": [28, 12, 878],
    "id": 559,
    "original_language": "en",
    "original_title": "Spider-Man 3",
    "overview":
        "The seemingly invincible Spider-Man goes up against an all-new crop of villains—including the shape-shifting Sandman. While Spider-Man’s superpowers are altered by an alien organism, his alter ego, Peter Parker, deals with nemesis Eddie Brock and also gets caught up in a love triangle.",
    "popularity": 16.71,
    "poster_path": "/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg",
    "release_date": "2007-05-01",
    "title": "Spider-Man 3",
    "video": false,
    "vote_average": 6.439,
    "vote_count": 14476,
  },
  {
    "adult": false,
    "backdrop_path": "/ac0kRKTfiJ4GcoUfb0XIO5vgC8q.jpg",
    "genre_ids": [28, 12, 878],
    "id": 1930,
    "original_language": "en",
    "original_title": "The Amazing Spider-Man",
    "overview":
        "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
    "popularity": 12.9531,
    "poster_path": "/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
    "release_date": "2012-06-23",
    "title": "The Amazing Spider-Man",
    "video": false,
    "vote_average": 6.7,
    "vote_count": 17740,
  },
  {
    "adult": false,
    "backdrop_path": null,
    "genre_ids": [18],
    "id": 148918,
    "original_language": "ro",
    "original_title": "Superman, Spider-Man sau Batman",
    "overview":
        "Aron, a 5-year-old boy, sets together with his worried father on a journey at the end of which he wishes, like the superheroes in the comic books, to save his mother suffering from a heart condition.",
    "popularity": 0.242,
    "poster_path": "/iUp85s5s7eaPbuCUNqOCeJCEVpY.jpg",
    "release_date": "2011-06-01",
    "title": "Superman, Spider-Man or Batman",
    "video": false,
    "vote_average": 6.9,
    "vote_count": 23,
  },
  {
    "adult": false,
    "backdrop_path": "/k0hlAzTryCYX1O1LyC6P8tAa8s0.jpg",
    "genre_ids": [28, 12, 878],
    "id": 102382,
    "original_language": "en",
    "original_title": "The Amazing Spider-Man 2",
    "overview":
        "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
    "popularity": 11.1362,
    "poster_path": "/dGjoPttcbKR5VWg1jQuNFB247KL.jpg",
    "release_date": "2014-04-16",
    "title": "The Amazing Spider-Man 2",
    "video": false,
    "vote_average": 6.5,
    "vote_count": 13575,
  },
  {
    "adult": false,
    "backdrop_path": "/34jW8LvjRplM8Pv06cBFDpLlenR.jpg",
    "genre_ids": [28, 12, 878],
    "id": 429617,
    "original_language": "en",
    "original_title": "Spider-Man: Far From Home",
    "overview":
        "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
    "popularity": 16.7884,
    "poster_path": "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    "release_date": "2019-06-28",
    "title": "Spider-Man: Far From Home",
    "video": false,
    "vote_average": 7.409,
    "vote_count": 16100,
  },
  {
    "adult": false,
    "backdrop_path": "/vqZnytUpDDAZI6JU7WtCqdq84L.jpg",
    "genre_ids": [28, 12, 878],
    "id": 558,
    "original_language": "en",
    "original_title": "Spider-Man 2",
    "overview":
        "Peter Parker is going through a major identity crisis. Burned out from being Spider-Man, he decides to shelve his superhero alter ego, which leaves the city suffering in the wake of carnage left by the evil Doc Ock. In the meantime, Parker still can't act on his feelings for Mary Jane Watson, a girl he's loved since childhood. A certain anger begins to brew in his best friend Harry Osborn as well...",
    "popularity": 7.915,
    "poster_path": "/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg",
    "release_date": "2004-06-25",
    "title": "Spider-Man 2",
    "video": false,
    "vote_average": 7.294,
    "vote_count": 15522,
  },
  {
    "adult": false,
    "backdrop_path": "/zlpZzccypkAYFZIyYLQcchl90ZC.jpg",
    "genre_ids": [878, 28, 80, 10770],
    "id": 225914,
    "original_language": "en",
    "original_title": "Spider-Man",
    "overview":
        "When an extortionist threatens to force a multi-suicide unless a huge ransom is paid, only Peter Parker can stop him with his new powers as Spider-Man.",
    "popularity": 1.3535,
    "poster_path": "/jNxRHZ2cxVkNRtxgHuCtv7GY4JP.jpg",
    "release_date": "1977-09-14",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 6.3,
    "vote_count": 197,
  },
  {
    "adult": false,
    "backdrop_path": "/rRXye7JBRcKaqc0KfchNUCBNoDE.jpg",
    "genre_ids": [16, 12, 28, 10770, 80],
    "id": 270768,
    "original_language": "en",
    "original_title": "Daredevil vs. Spider-Man",
    "overview": "Spider-Man and Daredevil team up to fight Kingpin.",
    "popularity": 1.6504,
    "poster_path": "/mEtyZBbVl0sx0y1blYuVDgeNLkr.jpg",
    "release_date": "2003-02-11",
    "title": "Daredevil vs. Spider-Man",
    "video": true,
    "vote_average": 7.5,
    "vote_count": 116,
  },
  {
    "adult": false,
    "backdrop_path": "/40RZP4mEel441OVcNyFCTFzHi4o.jpg",
    "genre_ids": [16],
    "id": 50410,
    "original_language": "en",
    "original_title": "Spider-Man: The Venom Saga",
    "overview":
        "A space-shuttle crash-landing puts the famous web-slinger Spider-Man in contact with a living alien substance that bonds to his suit and enhances his super-powers. Unfortunately, the alien substance begins to change him and he feels the pull of evil, so discards the suit. The evil attaches itself to another host leading to an epic confrontation between good and evil.",
    "popularity": 1.7039,
    "poster_path": "/vvYt1CDagCKMrolohME0o15GPZ3.jpg",
    "release_date": "2005-06-07",
    "title": "Spider-Man: The Venom Saga",
    "video": true,
    "vote_average": 6.956,
    "vote_count": 91,
  },
  {
    "adult": false,
    "backdrop_path": "/63JYqhefGrbVg0YqZ3xWqn0pwT2.jpg",
    "genre_ids": [878, 28, 12],
    "id": 969681,
    "original_language": "en",
    "original_title": "Spider-Man: Brand New Day",
    "overview":
        "The fourth installment in the MCU Spider-Man franchise. Plot TBA.",
    "popularity": 4.6692,
    "poster_path": "/9JCQtDCSpPR2ld55yNlEg1VwcQo.jpg",
    "release_date": "2026-07-30",
    "title": "Spider-Man: Brand New Day",
    "video": false,
    "vote_average": 0,
    "vote_count": 0,
  },
  {
    "adult": false,
    "backdrop_path": "/gC4srY5pUJ2zpo6lxWiedCUKzDc.jpg",
    "genre_ids": [],
    "id": 68658,
    "original_language": "en",
    "original_title": "Spiderman",
    "overview":
        "One minute he's Peter Parker the college student, and the next he's Spiderman!",
    "popularity": 0.0289,
    "poster_path": "/3HakxkortobYPDd7tRqKWM9PyxQ.jpg",
    "release_date": "1990-01-01",
    "title": "Spider-Man",
    "video": false,
    "vote_average": 8,
    "vote_count": 31,
  },
  {
    "adult": false,
    "backdrop_path": null,
    "genre_ids": [9648],
    "id": 397831,
    "original_language": "ja",
    "original_title": "殺人鬼 蜘蛛男",
    "overview": "Adaptation of Edogawa Ranpo's novel.",
    "popularity": 0.403,
    "poster_path": "/8qqeiVkNHjLOVu0jvRr44UbAvkF.jpg",
    "release_date": "1958-06-29",
    "title": "The Spider-Man",
    "video": false,
    "vote_average": 4.8,
    "vote_count": 3,
  },
  {
    "adult": false,
    "backdrop_path": "/xgjdA09pWlMdZiMOn5Z51IkDUE3.jpg",
    "genre_ids": [12, 99],
    "id": 501784,
    "original_language": "fr",
    "original_title": "La Légende de L'Homme Araignée",
    "overview":
        "Alain Robert - aka the “French Spiderman” – climbs all kind of skyscraper (to the great joy of the public and the despair of the police) with a weakness for the highest ones like the Sears Towers in Chicago, the Petronas Towers in Kuala Lumpur or Taipei 101 in Taiwan.  With his short frame and at almost 50, Alain is a physical phenomenon capable of hoisting his body with only one finger despite a major disability due to a fall in 1982. Paradoxically, it is after that accident that he developed his style of climbing using only his bare hands and without any security.  Today, with more than 100 towers climbed, as many arrests and several stays in prison, Alain is a legend. But who’s the man behind the climber? What motivates him? Find out in this portrait full of breathtaking footage.",
    "popularity": 0.0988,
    "poster_path": "/y4xMpBRU8kWXgF6VVGQpRuOSfEU.jpg",
    "release_date": "2009-04-04",
    "title": "Legend of the Spider-Man",
    "video": false,
    "vote_average": 10,
    "vote_count": 1,
  },
  {
    "adult": false,
    "backdrop_path": "/smp0JlTfUt0Esr7eKyroSeC8Ur6.jpg",
    "genre_ids": [16, 28, 12, 878],
    "id": 911916,
    "original_language": "en",
    "original_title": "Spider-Man: Beyond the Spider-Verse",
    "overview":
        "Miles Morales is now a fugitive on the run from every other Spider in the multiverse, and Gwen and his other friends might not be enough to help him.",
    "popularity": 4.6061,
    "poster_path": "/rZ4arzyaDyI8l9Y7VIPPsDGARwh.jpg",
    "release_date": "2027-06-02",
    "title": "Spider-Man: Beyond the Spider-Verse",
    "video": false,
    "vote_average": 0,
    "vote_count": 0,
  },
];

final List<Downloads> topIdleSearch = topIdle
    .map((movieMap) => Downloads.fromJson(movieMap))
    .toList();

final List<SearchResultData> searchesResult = searches
    .map((movieMap) => SearchResultData.fromJson(movieMap))
    .toList();

@freezed
abstract class SearchState with _$SearchState {
  const factory SearchState({
    required List<SearchResultData> searchResultList,
    required List<Downloads> idleList,
    required bool isLoading,
    required bool isError,
  }) = _SearchState;

  factory SearchState.initial() => SearchState(
    searchResultList: searchesResult,
    idleList: topIdleSearch,
    isLoading: false,
    isError: false,
  );
}
